app:
  name: kuberpc-client
  namespace: kuberpc-dev
  replicas: 1
  rpcPort: 8092
  httpPort: 8091
  image:
    repository: docker.io/darksueii/kuberpc_client_simulator
    tag: latest
    pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP

secret:
  name: kuberpc-client-secret
  data:
    RPC_PORT: "8092"
    HTTP_PORT: "8091"
    KUBERPC_CORE: "http://kuberpc-core.kuberpc-dev.svc.cluster.local:8080"
    SERVICE_NAME: "kuberpc-server"
