app:
  name: kuberpc-server
  namespace: kuberpc-dev
  replicas: 1
  rpcPort: 8082
  httpPort: 8081
  image:
    repository: docker.io/darksueii/test_kuberpc
    tag: latest
    pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP
