app:
  name: kuberpc-server
  namespace: kuberpc-dev
  replicas: 1
  rpcPort: 8082
  httpPort: 8081
  image:
    repository: docker.io/darksueii/kuberpc_server_simulator
    tag: latest
    pullPolicy: Always

service:
  type: ClusterIP
  protocol: TCP

secret:
  name: kuberpc-server-secret
  data:
    RPC_HOST: "kuberpc-server.kuberpc-dev.svc.cluster.local"
    RPC_PORT: "8082"
    HTTP_PORT: "8081"
    KUBERPC_CORE: "http://kuberpc-core.kuberpc-dev.svc.cluster.local:8080"
    SERVICE_NAME: "kuberpc-server"
