apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:
    - name: rpc-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.app.rpcPort }}
      targetPort: {{ .Values.app.rpcPort }}
    - name: http-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.app.httpPort }}
      targetPort: {{ .Values.app.httpPort }}